### ISSUE TITLE
Download for chrome opens a error page

### ISSUE THREAD

**Issue by itizarsa** [thingbomb/flowtide#32]
**Describe the bug**

When clicking download for chrome, it goes to https://chromewebstore.google.com/detail/error

**To Reproduce**

1. Go to https://www.flowtide.app on Chrome
2.  Click Download For Chrome
3. Opens https://chromewebstore.google.com/detail/error

**Expected behavior**

Should redirect to https://chromewebstore.google.com/detail/flowtide-beautiful-new-ta/fpdjjjmglibdjocjpcchgkbakeelaghm

**Screenshots**

![error](https://github.com/user-attachments/assets/0873a6c3-9f33-44e7-bc32-e2ce8ef459ec)

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome
- Version: 131.0.6778.109 (Official Build) (arm64)

**Comment by georg-stone** [comment]
The issue has since been fixed. If this happens again, please let me know.
